### PR TITLE
Create FindCycleInGraph.cpp

### PR DESCRIPTION
**Pull request by rohith1125**
Cpp code to detect cycles in a graph

### CODE REVIEW

**Comment by rohith1125** [comment]
@SamarjeetBanik Have a look

**Comment by SamarjeetBanik** [comment]
No comments found! Please add proper and understandable comments to your program.

**Review by rohith1125 — COMMENTED** [review]
@SamarjeetBanik have a look

**Comment by SamarjeetBanik** [comment]
Please add your name in the contributor's list. (Contributors.md)

**Comment by rohith1125** [comment]
> Please add your name in the contributor's list. (Contributors.md)

@SamarjeetBanik already added

**Pull request merged**
