### PR TITLE
Added N-Queens Problem in Backtracking

### PR DESCRIPTION
**Pull request by sah16**

### CODE REVIEW

**Comment by SamarjeetBanik** [comment]
No comments found! Kindly add proper and understandable comments throughout the program.

**Comment by SamarjeetBanik** [comment]
After resolving the above issue, kindly also add your name in the contributors list. (Contributors.md)

**Comment by sah16** [comment]
The program now has comments explaining it and it also has its problem statement with a sample input and output, name has been added in Contributors.md

**Comment by SamarjeetBanik** [comment]
Thanks for your contribution.

**Pull request merged**
