### PR TITLE
Feat: Added Quick Sort algorithm

### PR DESCRIPTION
**Pull request by Pulkit007**

### CODE REVIEW

**Comment by SamarjeetBanik** [comment]
Kindly add your name in the contributors list. (Contributors.md)

**Comment by Pulkit007** [comment]
> Kindly add your name in the contributors list. (Contributors.md)

Should I make a new PR for this?

**Comment by SamarjeetBanik** [comment]
You can do within this on-going PR also. Just make changes in Contributors.md and commit, it will get updated with the current one. Then I would merge.

**Comment by Pulkit007** [comment]
> You can do within this on-going PR also. Just make changes in Contributors.md and commit, it will get updated with the current one. Then I would merge.

I was facing some issues, so I created a new PR for that. Please merge this.
Here is the link https://github.com/SamarjeetBanik/get-your-PR-accepted/pull/35

**Comment by SamarjeetBanik** [comment]
Ok

**Pull request merged**
