### PR TITLE
Create Binary Search without Recursion in Python

### PR DESCRIPTION
**Pull request by ayushsaxena119**

### CODE REVIEW

**Comment by ayushsaxena119** [comment]
Review changes and revert feedback.

**Comment by SamarjeetBanik** [comment]
Please add proper commenting! No comments found in the program.

**Comment by ayushsaxena119** [comment]
Added comments

**Comment by SamarjeetBanik** [comment]
Thanks for your contribution!

**Comment by SamarjeetBanik** [comment]
Kindly add your name in the Contributors.md file.

**Pull request merged**
