### PR TITLE
linear_search in c

### PR DESCRIPTION
**Pull request by Sharayu1071**
I added Linear Search in C. Please merge this.

### CODE REVIEW

**Comment by SamarjeetBanik** [comment]
No proper comments found! Please also look into the indentation.

**Comment by SamarjeetBanik** [comment]
After solving the above mentioned issue, kindly also add your name in the contributors list. (Contributors.md)

**Comment by Sharayu1071** [comment]
Okay I will do the changes asap.

**Comment by Sharayu1071** [comment]
added comments and indentation to code plz check.

**Comment by SamarjeetBanik** [comment]
Yes, that was a clean update. Appreciate your contribution!

**Comment by SamarjeetBanik** [comment]
Thanks for your contribution!

**Pull request merged**
