### PR TITLE
Add Shravya to Contributors list

### PR DESCRIPTION
**Pull request by ShravyaMallya**

### CODE REVIEW

**Comment by SamarjeetBanik** [comment]
Hey hello! Kindly contribute in the DS-Algo first, then add your name in the list.

**Comment by ShravyaMallya** [comment]
Hey!
Sorry about that.
I've updated the C folder with a Quick Sort algorithm's code.
Hope that works!

**Comment by SamarjeetBanik** [comment]
Ya, no problem, but your changes for quick sort in C is not reflecting. Kindly commit it in your own forked repo first then, PR here.

**Comment by ShravyaMallya** [comment]
I did.
I made another Pull request with updated changes.
Sorry about the inconvenience

**Comment by SamarjeetBanik** [comment]
No worries. I have sorted it out!

**Comment by SamarjeetBanik** [comment]
Thanks for your Contribution!

**Pull request merged**
