### PR TITLE
Adjacency list

### PR DESCRIPTION
**Pull request by Ashlesha01**
Graph Adjacency list

### CODE REVIEW

**Comment by SamarjeetBanik** [comment]
Please add comments.

**Comment by SamarjeetBanik** [comment]
Also add you name to contributors list. (Contributors.md)

**Comment by Ashlesha01** [comment]
Okay .

**Comment by Ashlesha01** [comment]
I have adhered to the changes . Please accept.

**Comment by SamarjeetBanik** [comment]
kindly also add your name in the contributors list. (Contributors.md)

**Comment by SamarjeetBanik** [comment]
Thanks for the contribution!

**Pull request merged**
